    
language: minimal

before_script:
    - export VERSION=${TRAVIS_BRANCH}  BUILDNUM=${TRAVIS_BUILD_NUMBER}
script:
    - docker-compose -f docker-compose.yml build

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker push goeasy-platform:latest
    on:
      branch: master
  - provider: script
    script: docker tag goeasy-platform sisayie/goeasy-platform:${TRAVIS_TAG} &&
      docker push sisayie/goeasy-platform:${TRAVIS_TAG}
    on:
      tags: true