    
language: minimal

before_script:
    - export VERSION=${TRAVIS_BRANCH}  BUILDNUM=${TRAVIS_BUILD_NUMBER}

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    - docker-compose -f docker-compose.yml build
  - provider: script
    script: docker push goeasy-platform:latest
    on:
      branch: master